export const HOME = '/'
export const EXPLORE = '/explore'
export const LATEST = '/latest'
export const NOTIFICATIONS = '/notifications'
export const MESSAGES = '/messages'
export const SETTINGS = 'settings'
export const PRIVACY = '/privacy'
export const SEARCH = '/search'

export const DISCORD = '/discord'